name: flutter_nocode_frontend
description: Flutter No-Code Builder Frontend Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.0.3
  flutter_speed_dial: ^7.0.0

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^16.2.0

  # HTTP & API
  dio: ^5.4.0
  dio_cache_interceptor: ^4.0.3

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # JSON & Serialization
  json_annotation: ^4.9.0
  equatable: ^2.0.5

  # UI Utilities
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Forms & Validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.2
  file_picker: ^10.3.2

  # Charts & Visualization
  fl_chart: ^1.0.0

  # Drag & Drop
  flutter_reorderable_grid_view: ^5.0.1
  drag_and_drop_lists: ^0.4.2

  # Code Editor
  code_editor: ^2.1.0

  # Toast & Notifications
  fluttertoast: ^8.2.4

  # Loading & Progress
  flutter_spinkit: ^5.2.0
  percent_indicator: ^4.2.3

  # Icons
  font_awesome_flutter: ^10.6.0

  # Image Picker
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700